name: Trigger Docker Build in Repo Two

on:
  workflow_dispatch:

jobs:
  call-repo2:
    uses: abhishek7015/two/.github/workflows/docker-build.yml@main
    with:
      environment: stage  # hardcoded, because you can't interpolate env here
    secrets: inherit
